apiVersion: apps/v1
kind: Deployment
metadata:
  name: one-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: one-app
  template:
    metadata:
      labels:
        app: one-app
    spec:
      containers:
        - name: one-container
          image: nginx:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: one-service
spec:
  selector:
    app: one-app
  ports:
    - port: 80
      targetPort: 80