apiVersion: apps/v1
kind: Deployment
metadata:
   name: two-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two-app
  template:
    metadata:
      labels:
        app:  two-app
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
           - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: two-service
spec:
  selector:
    app: two-app
  ports:
    - port: 80
      targetPort: 80
